#!/bin/bash
# XXX: -Xbootclasspath is used as JamVM runs 3x faster
# XXX: Java is symlink'd to here so the home button works
exec "$(dirname "$0")"/Java -Xmx8M -Xss256K -Xbootclasspath/p:/usr/share/java/sqlite.jar:/usr/share/java/jocstrap.jar -cp /usr/share/java/uicaboodle.jar:"$(dirname "$0")" com.saurik.uicaboodle.Main HelloJava "$@"
